# 1. Lý thuyết

**1) Để khởi tạo model trong tensorflow chúng ta sử dụng class nào?**

A. Sequential hoặc Model

B. Dense

C. Adam

D. Variable

**2) Điểm khác biệt giữa fit và fit_generator trong tensorflow là gì ?**

A. fit sẽ yêu cầu load toàn bộ dữ liệu lên RAM trong khi fit_generator sẽ sử dụng một hàm generator để sinh dữ liệu tại mỗi mini-batch. Từ đó giúp tiết kiệm bộ nhớ.

B. fit sẽ sử dụng hàm generator để sinh dữ liệu tại thời điểm huấn luyện còn fit_generator sẽ load toàn bộ dữ liệu.

C. fit sẽ huấn luyện model theo mini-batch còn fit_generator thì huấn luyện trên toàn bộ dataset.

D. trong hàm fit chúng ta có thể khai báo tập validation dataset còn trong fit_generator thì không.


**3) Các modules chính trong tensorflow dùng để xây dựng và huấn luyện model.**

A. `tf.keras.layers`: khởi tạo activation function; `tf.keras.Sequential`: khởi tạo model; `tf.keras.activations`: để khởi tạo các layers; `tf.keras.optimizers`: Khởi tạo optimizer cho bài toán tối ưu loss function; `tf.keras.losses`: khởi tạo loss function; `tf.keras.preprocessing`: Preprocessing data.

B. `tf.keras.layers`: để khởi tạo các layers; `tf.keras.Sequential`: khởi tạo model; `tf.keras.activations`: khởi tạo activation function; `tf.keras.optimizers`: Khởi tạo optimizer cho bài toán tối ưu loss function; `tf.keras.losses`: khởi tạo loss function; `tf.keras.preprocessing`: Preprocessing data.

C. `tf.keras.layers`: để khởi tạo các layers; `tf.keras.Sequential`: Preprocessing data; `tf.keras.activations`: khởi tạo activation function; `tf.keras.optimizers`: Khởi tạo optimizer cho bài toán tối ưu loss function; `tf.keras.losses`: khởi tạo loss function; `tf.keras.preprocessing`: khởi tạo model

D. `tf.keras.layers`: để khởi tạo các layers; `tf.keras.Sequential`: khởi tạo model; `tf.keras.activations`: khởi tạo activation function; `tf.keras.optimizers`: khởi tạo loss function; `tf.keras.losses`: Khởi tạo optimizer cho bài toán tối ưu loss function; `tf.keras.preprocessing`: Preprocessing data.


**4) Các bước trong huấn luyện model bao gồm:**

A. 1. Train/test data split --> 2. Initialize the optimizer algorithm --> 3. Build up model architecture --> 4. Train model on train --> 5. Evaluation on test --> 6. Save and use trained model

B. 1. Train/test data split --> 2. Build up model architecture --> 3. Train model on train --> 4. Initialize the optimizer algorithm --> 5. Evaluation on test --> 6. Save and use trained model

C. 1. Train/test data split --> 2. Build up model architecture --> 3. Initialize the optimizer algorithm --> 4. Evaluation on test --> 5. Train model on train --> 6. Save and use trained model

D. 1. Train/test data split --> 2. Build up model architecture --> 3. Initialize the optimizer algorithm --> 4. Train model on train --> 5. Evaluation on test --> 6. Save and use trained model

**5) Ý nghĩa của tham số epochs và batch_size trong huấn luyện mô hình là gì?**

A. epochs là kích thước của một mini-batch, batch_size là số lượt lặp lại toàn bộ dữ liệu khi huấn luyện.

B. epochs là số lượt lặp lại toàn bộ dữ liệu validation khi huấn luyện, batch_size là kích thước của một mini-batch.

C. epochs là số lượt lặp lại toàn bộ dữ liệu train khi huấn luyện, batch_size là kích thước của một mini-batch.

D. epochs là số lượng vòng lặp, mỗi vòng lặp là một lượt fit mini-batch, trên bộ dữ liệu khi huấn luyện; batch_size là kích thước của một mini-batch.

Answer:
<br/> 
1) A
<br/> 
2) A
<br/> 
3) B
<br/> 
4) D
<br/> 
5) D

#Chữa: Câu 5 đáp án đúng là C

# 2. Thực hành

6) Khởi tạo một tensor 3 chiều với định dạng là float và kích thước là 32x32x3

7) Nếu coi tensor trên là một bức ảnh RGB với số channel là 3 ở cuối. Hãy truy suất các ma trận ảnh tương ứng với mỗi kênh R, G, B.

8) Thực hiện tích hadamard và tích thông thường giữa ma trận R và G.

9) Từ bộ dữ liệu [Income-Classification](https://www.kaggle.com/t/090688c8d33a40b68be9e271d6ba6bae) hãy chuẩn hóa dữ liệu và phân chia tập train/test theo tỷ lệ 80/20. 

10) Xây dựng một mạng deep-neural-network để huấn luyện mô hình trên dữ liệu train và đánh giá mô hình trên dữ liệu test.


In [ ]:
import tensorflow as tf

In [ ]:
# 6/
A = tf.random.uniform([32, 32, 3])


In [ ]:
# 7/

In [ ]:
R = A[:,:,0]
R

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[0.12486768, 0.0095613 , 0.8173213 , ..., 0.8426049 , 0.6953224 ,
        0.37101078],
       [0.21204221, 0.44715917, 0.7763243 , ..., 0.82795906, 0.07950962,
        0.8597264 ],
       [0.8736856 , 0.12800407, 0.6763798 , ..., 0.31176496, 0.39129663,
        0.23603451],
       ...,
       [0.06896603, 0.64819443, 0.68998635, ..., 0.35441124, 0.81247246,
        0.01808214],
       [0.9225533 , 0.04895926, 0.3367356 , ..., 0.48570597, 0.9226358 ,
        0.45183825],
       [0.59546006, 0.7632868 , 0.6676011 , ..., 0.48411858, 0.29704702,
        0.4419042 ]], dtype=float32)>

In [ ]:
G = A[:,:,1]
G

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[0.9061973 , 0.1846999 , 0.05399585, ..., 0.19218409, 0.9729698 ,
        0.7968621 ],
       [0.9560739 , 0.57823396, 0.86155236, ..., 0.7196903 , 0.556795  ,
        0.53180695],
       [0.00611627, 0.18339407, 0.37226868, ..., 0.23088598, 0.7056761 ,
        0.59848344],
       ...,
       [0.45819902, 0.06473172, 0.34236622, ..., 0.25723302, 0.3212222 ,
        0.48606443],
       [0.9920677 , 0.53327334, 0.11464751, ..., 0.708712  , 0.73020077,
        0.39004087],
       [0.02080035, 0.7712071 , 0.88363135, ..., 0.25101578, 0.08701682,
        0.32370317]], dtype=float32)>

In [ ]:
B = A[:,:,2]
B

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[0.8111317 , 0.3232442 , 0.9760299 , ..., 0.6121105 , 0.6928469 ,
        0.39543664],
       [0.79135585, 0.56226075, 0.59132063, ..., 0.1088413 , 0.8586384 ,
        0.99019   ],
       [0.88477206, 0.25466156, 0.6833557 , ..., 0.36264563, 0.70936847,
        0.12429655],
       ...,
       [0.8977933 , 0.26579058, 0.02127767, ..., 0.21807122, 0.7317529 ,
        0.7527286 ],
       [0.53135335, 0.8303032 , 0.61095536, ..., 0.33586383, 0.6110617 ,
        0.94064856],
       [0.8414519 , 0.37817395, 0.16511428, ..., 0.77606094, 0.04186964,
        0.11370802]], dtype=float32)>

In [ ]:
# 8/
hadamard = R * G
hadamard

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[0.11315475, 0.00176597, 0.04413196, ..., 0.16193525, 0.6765277 ,
        0.29564443],
       [0.20272802, 0.25856262, 0.668844  , ..., 0.59587413, 0.04427056,
        0.45720848],
       [0.0053437 , 0.02347519, 0.25179502, ..., 0.07198216, 0.27612868,
        0.14126275],
       ...,
       [0.03160017, 0.04195874, 0.23622802, ..., 0.09116627, 0.26098418,
        0.00878909],
       [0.91523534, 0.02610867, 0.0386059 , ..., 0.34422565, 0.6737094 ,
        0.1762354 ],
       [0.01238578, 0.5886522 , 0.58991325, ..., 0.12152141, 0.02584809,
        0.14304578]], dtype=float32)>

In [ ]:
# 9

###**Setup**


In [ ]:
!pip install -q kaggle

from google.colab import files

files.upload()

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c ml-hands-on-python-kaggle-01

Saving kaggle.json to kaggle (3).json
train.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
sample_submission.csv: Skipping, found more recently modified local copy (use --force to force download)
test.csv: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
!unzip train.csv.zip

Archive:  train.csv.zip
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: train.csv               


In [ ]:
!pip install --upgrade category_encoders

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, Normalizer, QuantileTransformer, OneHotEncoder, OrdinalEncoder, LabelEncoder
import category_encoders as ce

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [ ]:
train 

ID  age         work_type  ...  hrs_per_week nationality  target_income
0          0   45           Private  ...            40          US              0
1          1   23           Private  ...            30          US              0
2          2   22           Private  ...            20       South              0
3          3   27           Private  ...            40          US              0
4          4   18           Private  ...            20          US              0
...      ...  ...               ...  ...           ...         ...            ...
24995  24995   47         State-gov  ...            45          US              1
24996  24996   23           Private  ...            35          US              0
24997  24997   24           Private  ...            35          US              0
24998  24998   44  Self-emp-not-inc  ...            55          US              0
24999  24999   42                 ?  ...            22     Ecuador              0

[25000 rows x 16 columns]

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   25000 non-null  int64 
 1   age                  25000 non-null  int64 
 2   work_type            25000 non-null  object
 3   final_weight         25000 non-null  int64 
 4   education            25000 non-null  object
 5   total_education_yrs  25000 non-null  int64 
 6   marital_state        25000 non-null  object
 7   job                  25000 non-null  object
 8   status               25000 non-null  object
 9   ethnicity            25000 non-null  object
 10  sex                  25000 non-null  object
 11  capital_gain         25000 non-null  int64 
 12  capital_loss         25000 non-null  int64 
 13  hrs_per_week         25000 non-null  int64 
 14  nationality          25000 non-null  object
 15  target_income        25000 non-null  int64 
dtypes: i

In [ ]:
train.describe()

ID           age  ...  hrs_per_week  target_income
count  25000.000000  25000.000000  ...  25000.000000    25000.00000
mean   12499.500000     38.568800  ...     40.392200        0.23944
std     7217.022701     13.642694  ...     12.350547        0.42675
min        0.000000     17.000000  ...      1.000000        0.00000
25%     6249.750000     28.000000  ...     40.000000        0.00000
50%    12499.500000     37.000000  ...     40.000000        0.00000
75%    18749.250000     48.000000  ...     45.000000        0.00000
max    24999.000000     90.000000  ...     99.000000        1.00000

[8 rows x 8 columns]

In [ ]:
numerical_feats = train.dtypes[train.dtypes != "object"].index
print("Number of Numerical features: ", len(numerical_feats))

categorical_feats = train.dtypes[train.dtypes == "object"].index
print("Number of Categorical features: ", len(categorical_feats))

Number of Numerical features:  8
Number of Categorical features:  8


In [ ]:
for catg in list(categorical_feats):
    print("Feature categories: ", catg)
    print(train[catg].value_counts())
    print('#'*50)

Feature categories:  work_type
Private             17537
Self-emp-not-inc     1930
Local-gov            1592
?                    1379
State-gov             964
Self-emp-inc          851
Federal-gov           732
Without-pay            10
Never-worked            5
Name: work_type, dtype: int64
##################################################
Feature categories:  education
HS-grad         8060
Some-college    5672
Bachelors       4053
Masters         1323
Assoc-voc       1059
11th             871
Assoc-acdm       826
10th             728
7th-8th          466
Prof-school      460
9th              411
12th             333
Doctorate        307
5th-6th          263
1st-4th          130
Preschool         38
Name: education, dtype: int64
##################################################
Feature categories:  marital_state
Married-civ-spouse       11487
Never-married             8217
Divorced                  3416
Separated                  783
Widowed                    758
Married-spouse-a

In [ ]:
for num in list(numerical_feats) :
    print("Features Numeric: ", num)
    print(train[num].value_counts())
    print('#'*50)

Features Numeric:  ID
2047     1
17069    1
21135    1
10896    1
8849     1
        ..
11599    1
21840    1
23889    1
17746    1
0        1
Name: ID, Length: 25000, dtype: int64
##################################################
Features Numeric:  age
34    686
33    680
37    679
36    678
23    676
     ... 
83      4
88      3
85      2
87      1
86      1
Name: age, Length: 73, dtype: int64
##################################################
Features Numeric:  final_weight
123011    11
120131    10
193882    10
126675    10
241998    10
          ..
74977      1
190325     1
159604     1
284531     1
229376     1
Name: final_weight, Length: 17892, dtype: int64
##################################################
Features Numeric:  total_education_yrs
9     8060
10    5672
13    4053
14    1323
11    1059
7      871
12     826
6      728
4      466
15     460
5      411
8      333
16     307
3      263
2      130
1       38
Name: total_education_yrs, dtype: int64
###################

###**Data Wragling**

In [ ]:
def group_age(x):
    if x < 20:
        return "Under 20"
    elif x >= 20 and x < 30:
        return "20-29"
    elif x > 30 and x < 40:
        return "30-39"
    elif x >= 40 and x < 50:
        return "40-49"
    else:
        return "More than 50"

def group_nationality(x):
    if x == "US":
        return "US"
    elif x == "Mexico":
        return "Mexico"
    elif x == "Caribean":
        return "Caribean"
    elif x == "Germany":
        return "Germany"
    elif x == "UK":
        return "UK"
    else:
        return "Others"

In [ ]:
for df in [train, test]:
    # Age
    df["age"] = df["age"].apply(group_age)
    df["age"].astype("object")
    
    # Work type
    df["work_type"].replace("?", "Private", inplace=True)
    df["work_type"].replace(("Local-gov", "State-gov", "Federal-gov"), ("Government", "Government", "Government"), inplace=True)
    df["work_type"].replace(("Self-emp-not-inc", "Never-worked"), ("Without-pay", "Without-pay"), inplace=True)
    
    # Job
    train["job"].replace("?", "Other-service", inplace=True)
    
    # Education
    train["education"] = train["education"].replace(("9th", "10th", "11th", "12th"),("High-school","High-school", "High-school", "High-school"))
    train["education"] = train["education"].replace(("5th-6th", "7th-8th"),("Middle-school", "Middle-school"))
    train["education"] = train["education"].replace(("1st-4th"), "Elementary-school")
    train["education"].replace(('Preschool', 'High-school', 'Middle-school', 'Elementary-school'), ('Popular-program', 'Popular-program', 'Popular-program', 'Popular-program'), inplace=True)
    train["education"].replace(("Assoc-voc", "Assoc-acdm", "Some-college"), ("Assoc/College","Assoc/College", "Assoc/College"), inplace=True)
    train["education"].replace(("Prof-school", "Doctorate"), ("PhD", "PhD"), inplace=True)
    
    # Nationality
    train["nationality"] = train["nationality"].replace(("?", "Puerto-Rico"), ("US", "US"))
    train["nationality"] = train["nationality"].replace(("England", "Scotland", "Ireland"), ("UK", "UK", "UK"))
    train["nationality"] = train["nationality"].replace(("Jamaica", "Dominican-Republic", "Trinadad&Tobago"), ("Caribean", "Caribean", "Caribean"))
    train["nationality"] = train["nationality"].apply(group_nationality)

In [ ]:
def encode(frame, feature):
    # Encode categorical variables
    ordering = pd.DataFrame()
    ordering['val'] = frame[feature].unique()
    ordering.index = ordering.val

    ordering['ordering'] = range(1, ordering.shape[0]+1)
    ordering = ordering['ordering'].to_dict()
    
    for cat, o in ordering.items():
        frame.loc[frame[feature] == cat, feature+'_E'] = o

def Scaler(X_train, X_val, X_test, index_scaler=0):
    # Feature scaling 
    list_scaler = [MinMaxScaler(), StandardScaler(),  Normalizer(), QuantileTransformer()]
    
    scaler = list_scaler[index_scaler]
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)  
    X_test = scaler.transform(X_test)  
    return X_train, X_val, X_test

In [ ]:
numerical_feats = train.dtypes[train.dtypes != "object"].index
print("Number of Numerical features: ", len(numerical_feats))

categorical_feats = train.dtypes[train.dtypes == "object"].index
print("Number of Categorical features: ", len(categorical_feats))

Number of Numerical features:  7
Number of Categorical features:  9


In [ ]:
cate_encoded = []
for q in categorical_feats:  
    encode(train, q)
    encode(test, q)
    cate_encoded.append(q+'_E')
print(cate_encoded)

['age_E', 'work_type_E', 'education_E', 'marital_state_E', 'job_E', 'status_E', 'ethnicity_E', 'sex_E', 'nationality_E']


In [ ]:
train_feats = []
train_feats.extend(cate_encoded)
train_feats.extend(numerical_feats)
train_feats = [cols for cols in train_feats if cols != "ID" and cols != "target_income"]
train_feats

['age_E',
 'work_type_E',
 'education_E',
 'marital_state_E',
 'job_E',
 'status_E',
 'ethnicity_E',
 'sex_E',
 'nationality_E',
 'final_weight',
 'total_education_yrs',
 'capital_gain',
 'capital_loss',
 'hrs_per_week']

In [ ]:
test_feats = []
test_feats.extend(cate_encoded)
test_feats.extend(numerical_feats)
test_feats = [cols for cols in test_feats if cols != "ID" and cols != "target_income"]
test_feats

['age_E',
 'work_type_E',
 'education_E',
 'marital_state_E',
 'job_E',
 'status_E',
 'ethnicity_E',
 'sex_E',
 'nationality_E',
 'final_weight',
 'total_education_yrs',
 'capital_gain',
 'capital_loss',
 'hrs_per_week']

In [ ]:
X = train[train_feats]
X_test = test[test_feats]
y = train['target_income']

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3)

In [ ]:
X_train.shape

(17500, 14)

In [ ]:
X_val.shape

(7500, 14)

In [ ]:
X_train

age_E  work_type_E  ...  capital_loss  hrs_per_week
7708     2.0          1.0  ...             0            40
3504     2.0          1.0  ...             0            20
6019     2.0          3.0  ...             0            40
18555    5.0          1.0  ...             0            40
6426     2.0          3.0  ...             0            40
...      ...          ...  ...           ...           ...
17904    4.0          1.0  ...             0            60
10608    3.0          1.0  ...             0            12
15030    4.0          1.0  ...             0            40
2250     5.0          4.0  ...             0            98
7134     4.0          1.0  ...             0            40

[17500 rows x 14 columns]

In [ ]:
y_train

7708     1
3504     0
6019     0
18555    1
6426     0
        ..
17904    0
10608    0
15030    0
2250     1
7134     0
Name: target_income, Length: 17500, dtype: int64

In [ ]:
X_train, X_val, X_test = Scaler(X_train, X_val, X_test, 0)
X_train = X_train.astype('float32')
X_val = X_val.astype('float32')

In [ ]:
X_train

array([[0.25      , 0.        , 0.2       , ..., 0.        , 0.        ,
        0.39795917],
       [0.25      , 0.        , 0.2       , ..., 0.        , 0.        ,
        0.19387755],
       [0.25      , 0.6666667 , 0.8       , ..., 0.        , 0.        ,
        0.39795917],
       ...,
       [0.75      , 0.        , 0.6       , ..., 0.02105021, 0.        ,
        0.39795917],
       [1.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.9897959 ],
       [0.75      , 0.        , 0.2       , ..., 0.        , 0.        ,
        0.39795917]], dtype=float32)

In [ ]:
# 10

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization
from tensorflow.keras import utils
from tensorflow.keras import optimizers
import os



In [ ]:
checkpoint_path = "/content/save_model/model_nn.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    monitor='val_accuracy',
    save_weights_only=True,
    mode='max',
    save_best_only=True
)

# Set random seed for reproducability
tf.random.set_seed(1234)
initializer = tf.keras.initializers.RandomNormal()

In [ ]:
model = Sequential([
    Dense(32, activation='relu', input_dim = len(train_feats), kernel_initializer=initializer),
    BatchNormalization(),
    Dense(32, activation='relu', kernel_initializer=initializer),
    BatchNormalization(),
    Dense(32, activation='relu', kernel_initializer=initializer),
    BatchNormalization(),
    Dense(32, activation='relu', kernel_initializer=initializer),
    BatchNormalization(),
    Dense(1, activation='sigmoid')
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                480       
                                                                 
 batch_normalization (BatchN  (None, 32)               128       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 batch_normalization_1 (Batc  (None, 32)               128       
 hNormalization)                                                 
                                                                 
 dense_2 (Dense)             (None, 32)                1056      
                                                                 
 batch_normalization_2 (Batc  (None, 32)               1

In [ ]:
#hyper-parameters for optimizer
learning_rate = 1e-4
opt = optimizers.Adam(learning_rate=learning_rate)

model.compile(loss='categorical_crossentropy', 
              optimizer=opt, metrics=['accuracy'])

epochs = 50
history = model.fit(X_train, y_train, epochs=epochs, 
                    validation_data=(X_val, y_val), 
                    callbacks=[model_checkpoint_callback])

Epoch 1/50
544/547 [============================>.] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.7200
Epoch 00001: val_accuracy improved from -inf to 0.77093, saving model to /content/save_model/model_nn.ckpt
547/547 [==============================] - 4s 4ms/step - loss: 0.0000e+00 - accuracy: 0.7204 - val_loss: 0.0000e+00 - val_accuracy: 0.7709
Epoch 2/50
547/547 [==============================] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.7590
Epoch 00002: val_accuracy did not improve from 0.77093
547/547 [==============================] - 2s 4ms/step - loss: 0.0000e+00 - accuracy: 0.7590 - val_loss: 0.0000e+00 - val_accuracy: 0.7631
Epoch 3/50
546/547 [============================>.] - ETA: 0s - loss: 0.0000e+00 - accuracy: 0.7805
Epoch 00003: val_accuracy improved from 0.77093 to 0.78893, saving model to /content/save_model/model_nn.ckpt
547/547 [==============================] - 2s 4ms/step - loss: 0.0000e+00 - accuracy: 0.7806 - val_loss: 0.0000e+00 - val_accuracy: 0.7889
Epoch 4/50


In [ ]:
os.listdir(checkpoint_dir)

['model_nn.ckpt.data-00000-of-00001',
 'model_nn.ckpt.index',
 'checkpoint',
 'model_nn.ckpt']

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score
model.load_weights(checkpoint_path)
test_predict = model.predict(X_val)
test_predict = np.around(test_predict)

print("Accuracy:", accuracy_score(y_val, test_predict))

Accuracy: 0.8524


# Chữa:  CÓ thể đưa ra một vài nhận xét về mô hình, vẽ đồ thị acc, loss, confusion matrix,... Thử nghiệm thêm thay đổi tham số của mô hình