# 1. Lý thuyết

**1) Để khởi tạo model trong pytorch chúng ta sử dụng class nào?**

A. nn.Module

B. nn.Dense

C. nn.optim.Adam

D. nn.Dropout
</br>
Chọn A, kế thừa từ nn.Module.

**2) Để khởi tạo mạng neural network trong pytorch chúng ta cần làm gì ?**

A. Kế thừa lại class `nn.Model`. Khởi tạo các layers trong hàm tạo `__init__()` và sử dụng các layers để tính toán dữ liệu trong hàm `forward()`.

B. Khởi tạo một object của class `nn.Model` và sử dụng hàm `add()` để thêm từng layer vào mô hình.

C. Sử dụng class `nn.Model` để khởi tạo mô hình. Truyền vào bên trong class này một list gồm các layers.

D. Kế thừa lại class `nn.Module`. Khởi tạo các layers trong hàm tạo `__init__()` và sử dụng các layers để tính toán dữ liệu trong hàm `forward()`.

</br>
Chọn D. 

**3) Các modules chính trong pytorch dùng để xây dựng và huấn luyện model.**

A. `torch.nn`: Dùng để khởi tạo các layers và activations function và loss function, `torch.optim`: Khởi tạo optimizer, `torch.data`: Khởi tạo dataset và dataloader.

B. `torch.nn`: Dùng để khởi tạo các layers và activations function và loss function, `torch.optim`: Khởi tạo optimizer, `torch.utils.data`: Khởi tạo dataset và dataloader.

C. `torch.nn`: Dùng để khởi tạo các layers và activations function, `torch.optim`: Khởi tạo optimizer, `torch.data`: Khởi tạo dataset và dataloader, `torch.loss`: Khởi tạo loss function.

D. `torch.nn`: Dùng để khởi tạo các layers và loss function, `torch.optim`: Khởi tạo optimizer, `torch.data`: Khởi tạo dataset và dataloader, `torch.activations`: Khởi tạo activations function.

Chọn B.

**4) Để customize một Dataset trên pytorch chúng ta cần thực hiện như thế nào?**

A. Sử dụng thuộc tính `transformer` để qui định các biến đổi trên dữ liệu. Những biến đổi này được thực hiện trên hàm tạo.

B. Khởi tạo một class kế thừa lại `torch.utils.data.Dataset`. Khai báo các thuộc tính cần sử dụng trong hàm tạo của dataset như list đường dẫn, list label. Override lại hàm `__getitem__()` để thực hiện các xử lý trên dữ liệu.

C. Kế thừa lại một class `Dataset`. Các điều chỉnh trên dữ liệu được thực hiện trên hàm `transformer()`.

D. Sử dụng hàm `__getitem__()` để trả về toàn bộ các quan sát khi huấn luyện.

Chọn B.

**5) Ý nghĩa của tham số epochs và batch_size trong huấn luyện mô hình là gì?**

A. epochs là kích thước của một mini-batch, batch_size là số lượt lặp lại toàn bộ dữ liệu khi huấn luyện.

B. epochs là số lượt lặp lại toàn bộ dữ liệu validation khi huấn luyện, batch_size là kích thước của một mini-batch.

C. epochs là số lượt lặp lại toàn bộ dữ liệu train khi huấn luyện, batch_size là kích thước của một mini-batch.

D. epochs là số lượng vòng lặp, mỗi vòng lặp là một lượt fit mini-batch, trên bộ dữ liệu khi huấn luyện; batch_size là kích thước của một mini-batch.
</br>
Chọn C

# 2. Thực hành












6) Khởi tạo một tensor 3 chiều với định dạng là float và kích thước là 32x32x3

In [ ]:
import torch

In [ ]:
x = torch.randn(3,32,32) # 3 32 32 dimension is closer dimension to an image than 32 32 3 one

In [ ]:
x.shape

torch.Size([3, 32, 32])

7) Nếu coi tensor trên là một bức ảnh RGB với số channel là 3 ở cuối. Hãy truy suất các ma trận ảnh tương ứng với mỗi kênh R, G, B.

In [ ]:
R_channel = x[0]
G_channel = x[1]
B_channel = x[2]
R_channel.shape

torch.Size([32, 32])

In [ ]:
print("R_channel: \n{} ".format(R_channel))
print("G_channel: \n{}".format(G_channel))
print("B_channel:\n{}".format(B_channel))

R_channel: 
tensor([[-0.4439,  1.1791, -0.0494,  ...,  0.1314, -1.0900, -1.1552],
        [-0.2671, -1.5728,  1.3340,  ...,  0.0826, -0.3470, -0.9883],
        [-1.2039,  0.7003,  0.0161,  ..., -0.4349,  0.3561,  0.2048],
        ...,
        [ 0.1297, -0.1499, -0.8083,  ..., -0.4763, -1.3403, -0.2940],
        [ 1.5780,  1.5241, -0.0529,  ..., -0.3586,  1.0190,  0.9684],
        [ 0.7757,  0.7149, -0.3186,  ..., -0.3818,  2.0119,  0.1405]]) 
G_channel: 
tensor([[-0.3624,  1.8790,  0.3341,  ...,  1.5007,  0.1467, -0.5215],
        [-0.4674,  1.0595, -0.4222,  ...,  0.1825,  0.4517,  1.6744],
        [ 0.5699, -0.0443, -0.2575,  ..., -0.2160, -0.4150,  0.1225],
        ...,
        [ 1.6401,  0.3189,  0.5395,  ...,  2.0589,  0.3075,  0.4097],
        [-0.4372,  1.0793, -0.0483,  ..., -0.1955,  0.7248,  2.1783],
        [-0.9263,  1.2319, -0.6023,  ..., -0.0464, -0.2796, -0.3461]])
B_channel:
tensor([[ 0.4783,  0.3409, -1.0469,  ...,  1.2417, -0.5506,  0.3570],
        [-0.8972,  0.1300,

8) Thực hiện tích hadamard và tích thông thường giữa ma trận R và G.

In [ ]:
print("Hadamard product:")
print(R_channel * G_channel)

Hadamard product:
tensor([[ 0.1609,  2.2156, -0.0165,  ...,  0.1972, -0.1599,  0.6025],
        [ 0.1249, -1.6664, -0.5633,  ...,  0.0151, -0.1567, -1.6547],
        [-0.6861, -0.0310, -0.0041,  ...,  0.0939, -0.1478,  0.0251],
        ...,
        [ 0.2127, -0.0478, -0.4361,  ..., -0.9806, -0.4122, -0.1204],
        [-0.6900,  1.6449,  0.0026,  ...,  0.0701,  0.7385,  2.1095],
        [-0.7185,  0.8807,  0.1919,  ...,  0.0177, -0.5625, -0.0486]])


In [ ]:
print("Dot product:")
print(R_channel@G_channel)

Dot product:
tensor([[  0.2494,  -8.9346,  -0.3921,  ...,   5.3212,  -1.3442,   4.1304],
        [  4.1192,  -0.0137,  -8.2000,  ...,   0.2957,   0.2332, -10.0469],
        [ -0.3374,  -7.1513,   7.9485,  ..., -11.0176,  -1.8789,  -2.5448],
        ...,
        [  6.0839,  -6.8075,  -6.2469,  ...,   0.7093,   2.8253,  -9.6163],
        [  0.7143,   2.0328,   7.2291,  ...,  -8.3401,  -1.2399,   1.5140],
        [ -1.0151,   5.4739,  -9.4158,  ...,  11.6650,  -4.7728,  -0.4066]])


9) Từ bộ dữ liệu [Income-Classification](https://www.kaggle.com/t/090688c8d33a40b68be9e271d6ba6bae) hãy chuẩn hóa dữ liệu và phân chia tập train/test theo tỷ lệ 80/20. 

In [ ]:
%cd /content/drive/MyDrive/AI/Deeplearning_course/Week 3

/content/drive/MyDrive/AI/Deeplearning_course/Week 3


In [ ]:
import pandas as pd
data = pd.read_csv('./train.csv')

In [ ]:
data.head(10)

ID  age work_type  ...  hrs_per_week nationality  target_income
0   0   45   Private  ...            40          US              0
1   1   23   Private  ...            30          US              0
2   2   22   Private  ...            20       South              0
3   3   27   Private  ...            40          US              0
4   4   18   Private  ...            20          US              0
5   5   44   Private  ...            48          US              0
6   6   27   Private  ...            40          US              0
7   7   38   Private  ...            50          US              1
8   8   59   Private  ...            50          US              1
9   9   69         ?  ...            40          US              0

[10 rows x 16 columns]

In [ ]:
print(data.info())
print(data.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   25000 non-null  int64 
 1   age                  25000 non-null  int64 
 2   work_type            25000 non-null  object
 3   final_weight         25000 non-null  int64 
 4   education            25000 non-null  object
 5   total_education_yrs  25000 non-null  int64 
 6   marital_state        25000 non-null  object
 7   job                  25000 non-null  object
 8   status               25000 non-null  object
 9   ethnicity            25000 non-null  object
 10  sex                  25000 non-null  object
 11  capital_gain         25000 non-null  int64 
 12  capital_loss         25000 non-null  int64 
 13  hrs_per_week         25000 non-null  int64 
 14  nationality          25000 non-null  object
 15  target_income        25000 non-null  int64 
dtypes: i

In [ ]:
from sklearn.model_selection import train_test_split
label = data['target_income']
data = data.drop(['ID','target_income'],axis=1)
data_train, data_val, label_train, label_val = train_test_split(data, label, test_size=0.2, random_state=0)

In [ ]:
print("Shape of data train: {}".format(data_train.shape))
print("Shape of data validation: {}".format(data_val.shape))

Shape of data train: (20000, 14)
Shape of data validation: (5000, 14)


In [ ]:
# !pip install --upgrade category_encoders

10) Xây dựng một mạng deep-neural-network để huấn luyện mô hình trên dữ liệu train và đánh giá mô hình trên dữ liệu test.

In [ ]:
from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler, StandardScaler, RobustScaler, Normalizer
import category_encoders as ce
from sklearn.preprocessing import QuantileTransformer, PowerTransformer, OneHotEncoder

def feature_engineering(X_train, X_val, index_scaler=0):
    # Encode categorical variables
    cols = [ 'work_type', 
             'education', 
             'marital_state', 
             'job', 
             'status', 
             'ethnicity', 
             'sex', 
             'nationality'
            ]
    encoder = ce.OneHotEncoder(cols=cols)
    X_train = encoder.fit_transform(X_train)
    X_val = encoder.transform(X_val)
    
    # Feature scaling 
    list_scaler = [MinMaxScaler(), MaxAbsScaler(), StandardScaler(), 
                   RobustScaler(), Normalizer(), QuantileTransformer(), PowerTransformer()]
    
    scaler = list_scaler[index_scaler]
    X_train = scaler.fit_transform(X_train)
    X_val = scaler.transform(X_val)  
    return X_train, X_val

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
X_train, X_test = feature_engineering(data_train, data_val, index_scaler=0)
y_train, y_test = label_train, label_val

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(y_test.shape)

(20000, 108)
(20000,)
(5000,)


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [ ]:
## train data
class TrainData(Dataset):
    
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
        
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
        
    def __len__ (self):
        return len(self.X_data)


train_data = TrainData(torch.FloatTensor(X_train), 
                       torch.FloatTensor(y_train))

In [ ]:
## test data    
class TestData(Dataset):
    
    def __init__(self, X_data):
        self.X_data = X_data
        
    def __getitem__(self, index):
        return self.X_data[index]
        
    def __len__ (self):
        return len(self.X_data)
    

test_data = TestData(torch.FloatTensor(X_test))

In [ ]:
BATCH_SIZE = 64
train_loader = DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(dataset=test_data, batch_size=1)

In [ ]:
input_size = X_train.shape[1]
hl = 10
class income_network(nn.Module):
    def __init__(self):
        super(income_network, self).__init__()
        self.fc1 = nn.Linear(input_size,hl)
        self.fc2 = nn.Linear(hl,hl)
        self.batchnorm = nn.BatchNorm1d(hl)
        self.fc3 = nn.Linear(hl,1)
        
    def forward(self, inputs):
        x = torch.relu(self.fc1(inputs))
        x = self.batchnorm(x)
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        
        return x

In [ ]:

LEARNING_RATE = 0.001

model = income_network()
print(model)
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

income_network(
  (fc1): Linear(in_features=108, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=10, bias=True)
  (batchnorm): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
)


In [ ]:
def binary_acc(y_pred, y_test):
    y_pred_tag = torch.round(torch.sigmoid(y_pred))
    correct_results_sum = (y_pred_tag == y_test).sum().float()
    acc = correct_results_sum/y_test.shape[0]
    acc = torch.round(acc * 100)
    
    return acc

In [ ]:
EPOCHS = 10
model.train()
for e in range(1, EPOCHS+1):
    epoch_loss = 0
    epoch_acc = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch, y_batch
        optimizer.zero_grad()
        
        y_pred = model(X_batch)
        
        loss = criterion(y_pred, y_batch.unsqueeze(1))
        acc = binary_acc(y_pred, y_batch.unsqueeze(1))
        
        loss.backward()
        optimizer.step()
        
        epoch_loss += loss.item()
        epoch_acc += acc.item()
        
    print(f'Epoch {e+0:03}: | Loss: {epoch_loss/len(train_loader):.5f} | Acc: {epoch_acc/len(train_loader):.3f}')

Epoch 001: | Loss: 0.67769 | Acc: 81.230
Epoch 002: | Loss: 0.66841 | Acc: 83.345
Epoch 003: | Loss: 0.66612 | Acc: 83.805
Epoch 004: | Loss: 0.66362 | Acc: 84.217
Epoch 005: | Loss: 0.66236 | Acc: 84.358
Epoch 006: | Loss: 0.65987 | Acc: 84.812
Epoch 007: | Loss: 0.65817 | Acc: 84.869
Epoch 008: | Loss: 0.65764 | Acc: 84.994
Epoch 009: | Loss: 0.65613 | Acc: 85.131
Epoch 010: | Loss: 0.65520 | Acc: 85.112


In [ ]:
y_pred_list = []
model.eval()
with torch.no_grad():
    for X_batch in test_loader:
        X_batch = X_batch
        y_test_pred = model(X_batch)
        y_test_pred = torch.sigmoid(y_test_pred)
        y_pred_tag = torch.round(y_test_pred)
        y_pred_list.append(y_pred_tag.cpu().numpy())

y_pred_list = [a.squeeze().tolist() for a in y_pred_list]

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy on validation dataset: {}".format(accuracy_score(y_test, y_pred_list)))

Accuracy on validation dataset: 0.8496
